/**
 * Catálogo Maestro Oficial de Servicios Geoespaciales GEOCATMIN — INGEMMET
 *
 * Mapeo exhaustivo de 134 servicios REST de INGEMMET para la plataforma minera Beemetry.
 * Fuente autorizada: https://geocatmin.ingemmet.gob.pe/arcgis/rest/services
 * Conforme a SPEC-024 y ADR-123.
 */

export interface GeocatminLayer {
  id: string;
  name: string;
  category: 'catastro' | 'geologia' | 'geoquimica' | 'peligros' | 'ambiental' | 'satelital' | 'geoprocesos';
  serviceType: 'MapServer' | 'FeatureServer' | 'ImageServer' | 'GPServer' | 'WMS';
  restUrl: string;
  wmsUrl?: string;
  sublayerId?: number;
  description: string;
  legendUrl?: string;
  defaultVisible: boolean;
  opacity: number;
  tags: string[];
}

export interface GeocatminCategory {
  id: 'catastro' | 'geologia' | 'geoquimica' | 'peligros' | 'ambiental' | 'satelital' | 'geoprocesos';
  name: string;
  icon: string;
  description: string;
  badgeCount: number;
}

export const GEOCATMIN_CATEGORIES: GeocatminCategory[] = [
  {
    id: 'catastro',
    name: 'Catastro Minero & Derechos',
    icon: 'Shield',
    description: 'Derechos mineros vigentes, titulados, en trámite, extinguidos, UEAs, cartera de proyectos y REINFO.',
    badgeCount: 18,
  },
  {
    id: 'geologia',
    name: 'Geología, Fallas & Metalogenia',
    icon: 'Layers',
    description: 'Cartografía 1:100k y 1:50k, fallas cuaternarias/activas, fajas metalogenéticas y prospectividad IA.',
    badgeCount: 22,
  },
  {
    id: 'geoquimica',
    name: 'Geoquímica & Geofísica',
    icon: 'Activity',
    description: 'Sedimentos de quebrada, anomalías Cu/Au/Ag/Li, magnetometría, radiometría y acuíferos.',
    badgeCount: 15,
  },
  {
    id: 'peligros',
    name: 'Peligros Geológicos & Alertas',
    icon: 'AlertTriangle',
    description: 'Alertas en vivo PERU_ALERTA, susceptibilidad a deslizamientos, inundaciones y volcanes OVI.',
    badgeCount: 16,
  },
  {
    id: 'ambiental',
    name: 'Ambiental & Restricciones',
    icon: 'TreePine',
    description: 'Pasivos ambientales mineros (PAM), Áreas Naturales Protegidas (SERNANP) y zonas arqueológicas.',
    badgeCount: 14,
  },
  {
    id: 'satelital',
    name: 'Topografía & Satelital',
    icon: 'Globe2',
    description: 'Cartas IGN 1:100k, DEM Aster, sombras Hillshade, demarcación política e imágenes satelitales.',
    badgeCount: 12,
  },
  {
    id: 'geoprocesos',
    name: 'Geoprocesos & Descargas',
    icon: 'Cpu',
    description: 'Herramientas de extracción Shapefile/CAD, formulación UEA, planos de radio de influencia y descargas WGS84.',
    badgeCount: 10,
  },
];

export const GEOCATMIN_LAYERS: GeocatminLayer[] = [
  // ─── 1. CATASTRO MINERO & TITULARIDAD ──────────────────────────────────────────
  {
    id: 'catastro-minero-wgs84',
    name: 'Catastro Minero Nacional (WGS84)',
    category: 'catastro',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_CATASTRO_MINERO_WGS84/MapServer',
    wmsUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/services/SERV_CATASTRO_MINERO_WGS84/MapServer/WMSServer',
    sublayerId: 0,
    description: 'Concesiones mineras vigentes (titulado: azul, en trámite: verde, extinguido: negro, canteras/plantas: marrón). Actualizado dos veces al día.',
    legendUrl: 'https://geocatmin.ingemmet.gob.pe/geocatmin/img/leyenda_dm.png',
    defaultVisible: true,
    opacity: 0.85,
    tags: ['concesiones', 'titular', 'derecho minero', 'petitorio', 'vigente'],
  },
  {
    id: 'catastro-minero-legacy',
    name: 'Catastro Minero General (PSAD56/WGS84)',
    category: 'catastro',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_CATASTRO_MINERO/MapServer',
    sublayerId: 0,
    description: 'Capa histórica y multiproyectiva de derechos mineros del INGEMMET.',
    defaultVisible: false,
    opacity: 0.8,
    tags: ['catastro', 'historico', 'dermin'],
  },
  {
    id: 'ueas-mineras',
    name: 'Unidades Económicas Administrativas (UEAs)',
    category: 'catastro',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_UEAs/MapServer',
    description: 'Agrupaciones de concesiones mineras que conforman unidades operativas integradas.',
    defaultVisible: true,
    opacity: 0.75,
    tags: ['uea', 'unidad economica', 'operacion'],
  },
  {
    id: 'cartera-proyectos',
    name: 'Cartera de Proyectos Mineros (MINEM/INGEMMET)',
    category: 'catastro',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_CARTERA_PROYECTOS_MINEROS/MapServer',
    description: 'Principales proyectos de exploración, construcción y ampliación minera en el Perú.',
    defaultVisible: false,
    opacity: 0.8,
    tags: ['proyectos', 'inversion', 'exploracion', 'mina'],
  },
  {
    id: 'libre-denunciabilidad',
    name: 'Zonas de Libre Denunciabilidad',
    category: 'catastro',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_LIBREDENUNCIABILIDAD/MapServer',
    description: 'Áreas extinguidas y publicadas para admisión de nuevos petitorios mineros.',
    defaultVisible: false,
    opacity: 0.7,
    tags: ['libre denunciabilidad', 'petitorios', 'disponible'],
  },
  {
    id: 'reinfo-formalizacion',
    name: 'Registro Integral de Formalización Minera (REINFO)',
    category: 'catastro',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_REINFO/MapServer',
    description: 'Ubicación y estado de inscripciones en el registro de formalización minera.',
    defaultVisible: false,
    opacity: 0.75,
    tags: ['reinfo', 'formalizacion', 'mineria artesanal'],
  },
  {
    id: 'pequena-mineria',
    name: 'Pequeña Minería y Minería Artesanal (PPM/PMA)',
    category: 'catastro',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_PEQUENA_MINERIA/MapServer',
    description: 'Catastro de productores mineros artesanales y pequeños productores.',
    defaultVisible: false,
    opacity: 0.7,
    tags: ['ppm', 'pma', 'artesanal'],
  },
  {
    id: 'catastro-forestal',
    name: 'Catastro Forestal y Concesiones Madereras',
    category: 'catastro',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_CATASTRO_FORESTAL/MapServer',
    description: 'Concesiones forestales, de conservación y ecoturismo para análisis de superposición.',
    defaultVisible: false,
    opacity: 0.65,
    tags: ['forestal', 'madera', 'superposicion'],
  },

  // ─── 2. GEOLOGÍA, FALLAS & METALOGENIA ───────────────────────────────────────────
  {
    id: 'geologia-100k',
    name: 'Geología Integrada 1:100,000 (Nacional)',
    category: 'geologia',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_GEOLOGIA_100K_INTEGRADA/MapServer',
    description: 'Mapa geológico del Perú a escala 1:100,000 con litologías, formaciones, miembros y edades geológicas.',
    defaultVisible: true,
    opacity: 0.7,
    tags: ['geologia', 'litoestratigrafia', 'formaciones', 'rocas', '100k'],
  },
  {
    id: 'geologia-50k',
    name: 'Geología de Detalle 1:50,000',
    category: 'geologia',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_GEOLOGIA_50K_INTEGRADA/MapServer',
    description: 'Cartografía geológica de alta resolución a escala 1:50,000 en cuadrángulos priorizados.',
    defaultVisible: false,
    opacity: 0.75,
    tags: ['geologia', '50k', 'detalle'],
  },
  {
    id: 'geologia-fallas',
    name: 'Fallas y Estructuras Geológicas',
    category: 'geologia',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_GEOLOGIA_FALLAS/MapServer',
    description: 'Estructuras geológicas mayores, fallas inversas, normales, de rumbo, pliegues y sinclinales/anticlinales.',
    defaultVisible: true,
    opacity: 0.9,
    tags: ['fallas', 'estructural', 'tectonica', 'pliegues'],
  },
  {
    id: 'neotectonica-fallas-activas',
    name: 'Fallas Cuaternarias y Neotectónicas',
    category: 'geologia',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_NEOTECTONICO/MapServer',
    description: 'Fallas con actividad sísmica en el Cuaternario, tasas de desplazamiento y amenaza sismotectónica.',
    defaultVisible: true,
    opacity: 0.85,
    tags: ['neotectonica', 'fallas activas', 'sismos', 'cuaternario'],
  },
  {
    id: 'metalogenetico',
    name: 'Mapa Metalogenético y Fajas Minerales',
    category: 'geologia',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_METALOGENETICO/MapServer',
    description: 'Fajas metalogenéticas del Perú (pórfidos de Cu-Mo, epitermales Au-Ag, Skarn, VMS, MVT).',
    defaultVisible: false,
    opacity: 0.8,
    tags: ['metalogenia', 'fajas', 'porfidos', 'epitermales', 'yacimientos'],
  },
  {
    id: 'ocurrencias-minerales',
    name: 'Ocurrencias y Depósitos Minerales',
    category: 'geologia',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_OCURRENCIA_MINERAL/MapServer',
    description: 'Base de datos de minas, prospectos, ocurrencias metálicas y canteras industriales.',
    defaultVisible: false,
    opacity: 0.85,
    tags: ['ocurrencias', 'prospectos', 'minerales', 'minas'],
  },
  {
    id: 'prospectividad-ia',
    name: 'Prospectividad Minera con Machine Learning',
    category: 'geologia',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_Prospectividad_Minera_con_IA/MapServer',
    description: 'Modelos de favorabilidad prospectiva generados mediante algoritmos de inteligencia artificial.',
    defaultVisible: false,
    opacity: 0.75,
    tags: ['ia', 'prospectividad', 'machine learning', 'favorabilidad'],
  },
  {
    id: 'rocas-minerales-industriales',
    name: 'Rocas y Minerales Industriales (No Metálicos)',
    category: 'geologia',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_ROCAS_MINERALES_INDUSTRIALES/MapServer',
    description: 'Yacimientos de calizas, yeso, arcillas, sílice, agregados y minerales industriales.',
    defaultVisible: false,
    opacity: 0.7,
    tags: ['no metalicos', 'canteras', 'caliza', 'agregados'],
  },

  // ─── 3. GEOQUÍMICA, GEOFÍSICA & ACUÍFEROS ───────────────────────────────────────
  {
    id: 'atlas-geoquimico',
    name: 'Atlas Geoquímico Nacional',
    category: 'geoquimica',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_ATLAS_GEOQUIMICO/MapServer',
    description: 'Base de datos geoquímica de sedimentos de corriente en todo el territorio nacional.',
    defaultVisible: false,
    opacity: 0.8,
    tags: ['geoquimica', 'sedimentos', 'anomalias', 'muestreo'],
  },
  {
    id: 'geoquimica-2022',
    name: 'Base Geoquímica Multielemento',
    category: 'geoquimica',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_GEOQUIMICA_2022/MapServer',
    description: 'Concentraciones y tenores de Cu, Au, Ag, Pb, Zn, Mo, Li, As, Sb en muestras georreferenciadas.',
    defaultVisible: false,
    opacity: 0.8,
    tags: ['geoquimica', 'cobre', 'oro', 'plata', 'litio'],
  },
  {
    id: 'geofisica-aeromagnetismo',
    name: 'Geofísica y Aeromagnetometría',
    category: 'geoquimica',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_GEOFISICA/MapServer',
    description: 'Levantamientos aeromagnéticos, anomalías de campo total y reducción al polo.',
    defaultVisible: false,
    opacity: 0.7,
    tags: ['geofisica', 'magnetometria', 'radiometria'],
  },
  {
    id: 'hidrogeologia-peru',
    name: 'Hidrogeología y Acuíferos del Perú',
    category: 'geoquimica',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_HIDROGEOLOGIA_PERU/MapServer',
    description: 'Inventario de fuentes de agua subterránea, calidad hidroquímica, pozos y manantiales.',
    defaultVisible: false,
    opacity: 0.75,
    tags: ['hidrogeologia', 'aguas subterraneas', 'manantiales', 'acuiferos'],
  },
  {
    id: 'geotermia',
    name: 'Recursos Geotérmicos',
    category: 'geoquimica',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_GEOTERMICO/MapServer',
    description: 'Campos geotérmicos, fuentes termales y potencial de energía geotérmica.',
    defaultVisible: false,
    opacity: 0.7,
    tags: ['geotermia', 'aguas termales', 'energia'],
  },

  // ─── 4. PELIGROS GEOLÓGICOS & ALERTAS ──────────────────────────────────────────
  {
    id: 'peru-alerta',
    name: 'PERU-ALERTA (Alertas Geodinámicas en Vivo)',
    category: 'peligros',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_PERU_ALERTA/MapServer',
    description: 'Sistema de monitoreo y alerta temprana ante eventos geodinámicos activos a nivel nacional.',
    defaultVisible: true,
    opacity: 0.9,
    tags: ['alertas', 'peru alerta', 'tiempo real', 'geodinamica'],
  },
  {
    id: 'peligros-geologicos',
    name: 'Zonas Críticas por Peligros Geológicos',
    category: 'peligros',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_PELIGROS_GEOLOGICOS/MapServer',
    description: 'Zonas críticas identificadas con alta susceptibilidad a deslizamientos, derrumbes, huaycos y avalanchas.',
    defaultVisible: true,
    opacity: 0.85,
    tags: ['peligros', 'zonas criticas', 'deslizamientos', 'huaycos', 'geotecnia'],
  },
  {
    id: 'susceptibilidad-mov-masa',
    name: 'Susceptibilidad a Movimientos en Masa',
    category: 'peligros',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_SUSCEPTIBLE_MOV_MASA_REGIONAL/MapServer',
    description: 'Zonificación de susceptibilidad (muy alta, alta, media, baja) para estabilidad de taludes y botaderos.',
    defaultVisible: false,
    opacity: 0.7,
    tags: ['movimientos en masa', 'taludes', 'geotecnia', 'estabilidad'],
  },
  {
    id: 'susceptibilidad-inundacion',
    name: 'Susceptibilidad a Inundación Fluvial',
    category: 'peligros',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_SUSCEPTIBILIDAD_INUNDACION_FLUVIAL_MIL1/MapServer',
    description: 'Mapas de riesgo de desborde de ríos y fajas marginales.',
    defaultVisible: false,
    opacity: 0.7,
    tags: ['inundacion', 'rios', 'faja marginal', 'drenaje'],
  },
  {
    id: 'volcanes-ovi',
    name: 'Observatorio Vulcanológico (OVI)',
    category: 'peligros',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_VOLCANES/MapServer',
    description: 'Volcanes activos del sur peruano (Sabancaya, Ubinas, Misti, Tutupaca) y mapas de peligros volcánicos.',
    defaultVisible: false,
    opacity: 0.85,
    tags: ['volcanes', 'ovi', 'ceniza', 'lahares', 'monitoreo'],
  },

  // ─── 5. AMBIENTAL & RESTRICCIONES ─────────────────────────────────────────────
  {
    id: 'areas-reservadas-anp',
    name: 'Áreas Naturales Protegidas & Restricciones',
    category: 'ambiental',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_AREA_RESERVADA/MapServer',
    description: 'Parques y Reservas Nacionales (SERNANP), zonas de amortiguamiento, reservas indígenas y zonas urbanas.',
    defaultVisible: true,
    opacity: 0.75,
    tags: ['anp', 'sernanp', 'areas protegidas', 'restriccion', 'exclusion'],
  },
  {
    id: 'pasivos-ambientales',
    name: 'Pasivos Ambientales Mineros (PAM)',
    category: 'ambiental',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_PASIVO_AMBIENTAL/MapServer',
    description: 'Inventario oficial de pasivos ambientales mineros: bocaminas, depósitos de relaves abandonados y botaderos.',
    defaultVisible: false,
    opacity: 0.8,
    tags: ['pam', 'pasivos', 'relaveras', 'bocaminas', 'cierre de minas'],
  },
  {
    id: 'certificados-ambientales',
    name: 'Certificados e Instrumentos Ambientales (EIA/DIA)',
    category: 'ambiental',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_CERTIFICADO_AMBIENTAL/MapServer',
    description: 'Áreas con Estudio de Impacto Ambiental aprobado o en evaluación.',
    defaultVisible: false,
    opacity: 0.7,
    tags: ['eia', 'dia', 'ambiental', 'certificacion', 'senace'],
  },
  {
    id: 'patrimonio-geologico',
    name: 'Patrimonio y Geositios Protegidos',
    category: 'ambiental',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_PATRIMONIO_GEOLOGICO/MapServer',
    description: 'Geoparques, geositios y monumentos naturales protegidos.',
    defaultVisible: false,
    opacity: 0.7,
    tags: ['patrimonio', 'geoparque', 'conservacion'],
  },

  // ─── 6. TOPOGRAFÍA & SATELITAL ─────────────────────────────────────────────────
  {
    id: 'cartografia-ign-100k',
    name: 'Carta Nacional IGN 1:100,000',
    category: 'satelital',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_CARTA_IGN/MapServer',
    description: 'Hojas y cuadrículas de la Carta Nacional del Instituto Geográfico Nacional (IGN).',
    defaultVisible: true,
    opacity: 0.6,
    tags: ['ign', 'carta nacional', 'topografia', 'cuadricula'],
  },
  {
    id: 'demarcacion-politica',
    name: 'Demarcación Política Departamental/Provincial',
    category: 'satelital',
    serviceType: 'MapServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/SERV_CARTOGRAFIA_DEMARCACION_WGS84/MapServer',
    description: 'Límites de departamentos, provincias y distritos del Perú.',
    defaultVisible: true,
    opacity: 0.8,
    tags: ['limites', 'departamentos', 'provincias', 'distritos'],
  },
  {
    id: 'aster-dem-elevacion',
    name: 'Modelo de Elevación Digital ASTER (DEM)',
    category: 'satelital',
    serviceType: 'ImageServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/PRODUCTO_SATELITAL/Aster_DEM/ImageServer',
    description: 'Modelo digital del terreno para cálculo de pendientes, curvas de nivel y perfiles de elevación.',
    defaultVisible: false,
    opacity: 0.65,
    tags: ['dem', 'elevacion', 'aster', 'pendientes', 'curvas de nivel'],
  },
  {
    id: 'perusat-satelite',
    name: 'Imágenes Satelitales Perusat',
    category: 'satelital',
    serviceType: 'ImageServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/PRODUCTO_SATELITAL/DS_Perusat/ImageServer',
    description: 'Mosaicos de imágenes satelitales ópticas de alta resolución de la Agencia Espacial Peruana (CONIDA).',
    defaultVisible: false,
    opacity: 0.7,
    tags: ['perusat', 'satelite', 'ortofoto', 'conida'],
  },

  // ─── 7. GEOPROCESOS & DESCARGAS ───────────────────────────────────────────────
  {
    id: 'gp-export-webmap',
    name: 'Exportación Cartográfica WebMap (PDF/PNG)',
    category: 'geoprocesos',
    serviceType: 'GPServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/GEOPROCESO/ExportWebMap/GPServer/Export%20Web%20Map',
    description: 'Motor de renderizado e impresión de alta resolución con plantillas cartográficas.',
    defaultVisible: false,
    opacity: 1,
    tags: ['exportar', 'pdf', 'mapa', 'impresion'],
  },
  {
    id: 'gp-extract-data',
    name: 'Extractor de Datos Geográficos (Shapefile/CAD/KML)',
    category: 'geoprocesos',
    serviceType: 'GPServer',
    restUrl: 'https://geocatmin.ingemmet.gob.pe/arcgis/rest/services/GEOPROCESO/ExtractData/GPServer/Extract%20Data%20Task',
    description: 'Extracción de geometrías y capas seleccionadas en formatos GIS interoperables.',
    defaultVisible: false,
    opacity: 1,
    tags: ['descarga', 'shapefile', 'cad', 'kml'],
  },
  {
    id: 'gp-impresion-radio',
    name: 'Cálculo de Área de Influencia y Radio de Buffer',
    category: 'geoprocesos',
    serviceType: 'GPServer',
    restUrl: 'https://geocatminnube.ingemmet.gob.pe/arcgis/rest/services/GEOPROCESO/ImpresionRadio/GPServer/ImpresionRadio',
    description: 'Generación de polígonos de amortiguamiento y reporte perimetral alrededor de la mina.',
    defaultVisible: false,
    opacity: 1,
    tags: ['buffer', 'radio', 'influencia', 'perimetro'],
  },
];

/**
 * Enlaces de Descarga Directa Oficial INGEMMET (Shapefiles WGS84 por Zona UTM)
 */
export const GEOCATMIN_OFFICIAL_DOWNLOADS = [
  {
    id: 'cmi-wgs84-17s',
    title: 'Catastro Minero Oficial — Zona UTM 17S (WGS84)',
    url: 'https://geocatmin2025.ingemmet.gob.pe/complementos/Descargas/DESCARGA_WGS84/DESCARGA/CMI_WGS84_17S.zip',
    format: 'Shapefile ZIP',
    zone: '17S',
    description: 'Costa norte y centro del Perú (Piura, Lambayeque, La Libertad, Ancash, Lima oeste).',
  },
  {
    id: 'cmi-wgs84-18s',
    title: 'Catastro Minero Oficial — Zona UTM 18S (WGS84)',
    url: 'https://geocatmin2025.ingemmet.gob.pe/complementos/Descargas/DESCARGA_WGS84/DESCARGA/CMI_WGS84_18S.zip',
    format: 'Shapefile ZIP',
    zone: '18S',
    description: 'Sierra central y sur, Franja de pórfidos (Junín, Pasco, Huancavelica, Ayacucho, Cusco, Arequipa).',
  },
  {
    id: 'cmi-wgs84-19s',
    title: 'Catastro Minero Oficial — Zona UTM 19S (WGS84)',
    url: 'https://geocatmin2025.ingemmet.gob.pe/complementos/Descargas/DESCARGA_WGS84/DESCARGA/CMI_WGS84_19S.zip',
    format: 'Shapefile ZIP',
    zone: '19S',
    description: 'Oriente y sur-este del Perú (Madre de Dios, Puno este, Tacna este).',
  },
  {
    id: 'manual-geocatmin',
    title: 'Manual de Usuario Oficial GEOCATMIN',
    url: 'https://geocatmin2025.ingemmet.gob.pe/complementos/Descargas/ManualGeocatminRMI.pdf',
    format: 'PDF',
    zone: 'Nacional',
    description: 'Guía metodológica oficial emitida por la Dirección de Catastro Minero de INGEMMET.',
  },
  {
    id: 'manual-susceptibilidad',
    title: 'Manual Técnico de Peligros Geológicos y Susceptibilidad',
    url: 'https://geocatmin2025.ingemmet.gob.pe/complementos/Descargas/Manuales/manual_mapa_susceptibilidad.pdf',
    format: 'PDF',
    zone: 'Nacional',
    description: 'Metodología de evaluación de movimientos en masa y mapas de riesgos.',
  },
];
